### ISSUE TITLE
Why are there so many node_modules shipped with it?

### ISSUE THREAD

**Issue by jjtbsomhorst** [timkouters/nl.timkouters.domitech#2]
Hi,

I just installed your app and what I noticed was the huge memory usage compared to other zwave device drivers. Could you explain why this is?

**Comment by timkouters** [comment]
Hi,

I still had a dependency with the Athom logging package. That made it way larger.
I've removed the dependency. 
New version will be out soon.

Fixed in 67eb5271a2116b2258567b592574bd7f48ad208f
