### ISSUE TITLE
Compatibiliy with Homey v2.0

### ISSUE THREAD

**Issue by RWensveen** [timkouters/nl.timkouters.domitech#3]
App currently is not compatible with Homey V2.0
To make ik compatible, the compatiblity restriction in app.json needs to be adapted:

old:    "compatibility": "1.x >=1.5.0",
new:       "compatibility": ">=1.5.0",

It looks like the app behaves the same in v1.5.13 and v2.0.

**Comment by timkouters** [comment]
Fixed in cb2ca5d2f7a747a5b81d82ad36d8fe6336d6b195
Thanks for the feedback :)
See you coming Monday
