### ISSUE TITLE
uk version ZB22UK

### ISSUE THREAD

**Issue by daesland** [timkouters/nl.timkouters.domitech#4]
I have just bought the uk version of the Domitech z-wave smart led light bulb.
It has a BC fitting.
When I add it to homey it just gets added as a generic device and is therefore just on/off with no dimming capability.
Is there anything you can do to help please?

Daniel

**Comment by timkouters** [comment]
Hi Daniel,

I've added the product ID of the UK-version as well in commit 435cc102d402dff50ef542122e10f2a5b19e76e5

It will take about a day or two to get it approved by Athom.
Please be aware you need to upgrade your Homey to version 2.0 before you can use the updated version of this app (1.0.7).
This can be by downloading the newest version of the homey app on: https://get.homey.app/
Let me know if you still have questions.

Kind regards,
Tim

**Comment by daesland** [comment]
Hi Tim

Just want to say a big thank you for that.
I have removed the bulbs and added them again and they dim as they should now.
I haven’t updated to version 2 though and it still works.
Not updating to version 2 until everything is ironed out with it.

Thanks again and for doing it so quickly.  Wish I had the know how to do stuff like that.

Daniel

**Comment by timkouters** [comment]
Hi Daniel,

You're most welcome.
Enjoy :)
