### ISSUE TITLE
Support for Homey Pro 2023

### ISSUE THREAD

**Issue by phgmhendrix** [timkouters/nl.timkouters.domitech#7]
Hi @timkouters , are you planning an update to sdk3?

**Comment by timkouters** [comment]
Hi,

Yes it was still in the planning.
Am / was a bit busy with rebuilding the house and work travels.

**Comment by Ray-Hoo** [comment]
Hi, I fully support this request: it would be great if you could upgrade this app to be compatible with homey pro 2023. I am using it a lot!

**Comment by Ray-Hoo** [comment]
I have made an update to SDK v3. It is running now on my Homey.

**Comment by mikalj2009** [comment]
Will the sdkv3 version be available for automatic upgrade via homey store anytime soon?

**Comment by phgmhendrix** [comment]
Is the testversion already available, I would really love to use it.

**Comment by timkouters** [comment]
Hi,

No not yet unfortunately.
I still have issues running the updated version.
I've contacted Raymond for a zip of his folder since I thing his
pull-request is missing files.

The error I still have:
[image: image.png]

Will keep you posted.

Kind regards,
Tim

Op zo 18 jun 2023 om 17:36 schreef Peter Hendrix ***@***.***>:

**Comment by phgmhendrix** [comment]
No problem here, it seems to work like a charm with the one change I mentioned in my previous comment.

**Comment by timkouters** [comment]
Hi,

I still get the same error after a clean git clone.
Can this be since I don't have a Homey Pro 2023 but an earlier Homey Pro?

Still to help you out, I've published for testing.

Kind regards,
Tim

**Comment by phgmhendrix** [comment]
Hi @timkouters, a clean git-clone won't work because there is a little error in the file app.json, it is missing a curly bracket on line 19.
In the picture below I have added it.
![image](https://github.com/timkouters/nl.timkouters.domitech/assets/11439882/4fda5eb7-6a9f-48bb-a4cd-6cd9c97e1826)

After that fix I installed the app via CLI and it works like a charm for me.

**Comment by timkouters** [comment]
@phgmhendrix, that fix I've pushed to master yesterday evening. Thanks for the heads-up.

The issue I have is still missing the homey-zwavedriver package at run-time.

**Comment by timkouters** [comment]
I've created a VM with a clean environment where I could run everything OK out of the box.
Now I see that the node_modules are taken along during packaging the App.
The issue resides in the 'npm list .' 

I'm going to re-install my laptop.
The app is awaiting approval from Athom.

Tim
